language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false
jobs:
  include:

  # Run build and tests on ARM64 on Pull Requests.
  # These tests are divided in half because their aggregate typical runtime
  # exceeds Travis' time limit (~60m) and were consistently causing timeouts.
  - stage: build
    name: "ARM64/Go1.16.x: make test [A-G]"
    if: type = pull_request
    os: linux
    arch: arm64
    dist: xenial
    go: 1.16.x
    env:
      - GO111MODULE=on
    script:
      - go run build/ci.go test -timeout 30m -coverage $(printf './%s/... ' $(go list ./... | sed 's|github.com/ethereum/go-ethereum||g' | cut -d'/' -f2 | uniq | grep -E '^[a-g]'))
  - stage: build
    name: "ARM64/Go1.16.x: make test [H-Z]"
    if: type = pull_request
    os: linux
    arch: arm64
    dist: xenial
    go: 1.16.x
    env:
      - GO111MODULE=on
    script:
      - go run build/ci.go test -timeout 30m -coverage $(printf './%s/... ' $(go list ./... | sed 's|github.com/ethereum/go-ethereum||g' | cut -d'/' -f2 | uniq | grep -E '^[h-z]'))
