name: "Go-Ethereum 1:1"
on:
  push:
    branches:
      - 'master'
jobs:
  compare:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Check out ethereum/go-ethereum code into the Go module directory
        uses: actions/checkout@v2
        with:
          repository: 'ethereum/go-ethereum'
          ref: 'v1.9.25'
          submodules: 'recursive' # Not necessary, but complete.

      - name: Fetch CoreGeth
        run: |
          git remote add etclabscore https://github.com/etclabscore/core-geth.git
          git fetch --depth 1 etclabscore master

      - name: Run Tests
        run: |
          git checkout etclabscore/master -- ethclient/ethclient_cg_test.go
          go test ./ethclient -run _CanCompareGoEthereum
